project_id = "hwomajdxcbtbsmbaucro"

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://lovable.dev", "http://localhost:5173"]
jwt_expiry = 3600

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[functions.send-contact-email]
verify_jwt = false

[functions.mpesa-payment]
verify_jwt = false